docker_daemon_config: 
  {
    "default-address-pools":
    [
      {"base":"172.29.2.0/16","size":24}
    ],  
    "bip": "172.29.2.1/24",
    "log-driver": "json-file",  
    "log-opts": {
      "max-size": "100m",
      "max-file": "5"  
    }
  }