---
- name: Register target host
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add EC2 to dynamic group
      add_host:
        name: "{{ target_host }}"
        groups: dynamic

- name: On-demand server provisioning
  hosts: dynamic
  become: true
  vars:
    ansible_user: "{{ target_user | default('ubuntu') }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - role: docker_engine
      when: install_docker | bool or install_nginx_proxy | bool or install_portainer_server | bool or install_portainer_agent | bool

    - role: nginx_proxy
      when: install_nginx_proxy | bool
    
    - role: portainer_server
      when: install_portainer_server | bool

    - role: portainer_agent
      when: install_portainer_agent | bool
      
    - role: verify
      when: >
        install_docker | bool or
        install_nginx_proxy | bool or
        install_portainer_server | bool or
        install_portainer_agent | bool