---
# For Static Inventory 
- name: On-demand server provisioning
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: docker_engine
      when: install_docker | bool

    - role: nginx_proxy
      when: install_nginx_proxy | bool

    - role: portainer_server
      when: install_portainer_server | bool

    - role: portainer_agent
      when: install_portainer_agent | bool

    - role: verify
      when: install_docker | bool or install_nginx_proxy | bool or install_portainer_agent | bool
