# roles/nginx_proxy/tasks/main.yml
---
- name: Create Nginx infrastructure directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /mnt-apps/nginx-proxy/nginx
    - /mnt-apps/nginx-proxy/vhost.d
    - /var/log/nginx/reverse-proxy
    - /etc/ssl/supalai_cert

# TODO: cert จะถือโดยคนอื่น รอ task แยกมาทีหลัง
- name: Copy SSL certificates
  ansible.builtin.copy:
    src: "{{ nginx_proxy_cert_src_dir }}/{{ item }}"   # อ่านจากเครื่องที่รัน playbook
    dest: "{{ nginx_proxy_cert_dir }}/{{ item }}"       # ไปวางที่ target host
    mode: '0644'
  loop: "{{ nginx_proxy_cert_files }}"

- name: Copy Nginx config files
  ansible.builtin.copy:
    src: "{{ nginx_proxy_config_src_dir }}/nginx/{{ item }}"
    dest: "/mnt-apps/nginx-proxy/nginx/{{ item }}"
    mode: '0644'
  loop:
    - proxy.conf
    - proxy-wide.conf

# TODO: vhost.d ยังไม่ใช้ตอนนี้
- name: Copy vhost.d configurations
  ansible.builtin.copy:
    src: "{{ nginx_proxy_config_src_dir }}/vhost.d/{{ item }}"
    dest: "/mnt-apps/nginx-proxy/vhost.d/{{ item }}"
    mode: '0644'
  when: lookup('fileglob', role_path + '/files/vhost.d/*') | length > 0

- name: Create Docker network nginx_proxy
  community.docker.docker_network:
    name: "nginx_proxy"
    state: present

- name: Deploy Nginx Proxy compose file
  ansible.builtin.copy:
    src: "{{ nginx_proxy_config_src_dir }}/compose.yaml"
    dest: /mnt-apps/nginx-proxy/compose.yaml
    mode: '0644'

- name: Run Nginx Proxy via docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ nginx_proxy_config_src_dir }}/compose.yaml"
    state: present
    
- name: Create logrotate config for nginx
  ansible.builtin.copy:
    content: |
      /var/log/nginx/reverse-proxy/*.log {
              monthly
              rotate 12
              compress
              delaycompress
              missingok
              notifempty
              create 644 root root
      }
    dest: /etc/logrotate.d/nginx-reverse-proxy-log
    mode: '0644'